### ISSUE TITLE
Six test files shadow the wish package with tools/wish.py, which stops the suite collecting

### ISSUE THREAD

**Issue by malcyon** [malcyon/wish#203]
Six test files put `tools/` on `sys.path` permanently, and `tools/wish.py` shadows the `wish` package when they do — which breaks collection for every test that imports `wish`.

## What breaks

`pytest` refuses to collect. Not one test failing: **collection is interrupted and nothing runs.**

```
ImportError: cannot import name 'backends' from 'wish' (/home/donald/src/wish/tools/wish.py)
ImportError: cannot import name 'debugmode' from 'wish' (...)
ImportError: cannot import name 'licenses' from 'wish' (...)
ImportError: cannot import name 'nativewatch' from 'wish' (...)
ImportError: cannot import name 'preferences' from 'wish' (...)
```

Seven modules go at once — `test_debuglog.py`, `test_debugmode.py`, `test_licenses.py`, `test_nativewatch.py`, `test_preferences.py`, `test_shotwindow.py` and `test_wish.py` — and `pytest` ends `Interrupted: 7 errors during collection`.

**Nobody playing Wish sees this.** What it costs is sessions: it happened on 2026-09-02, took an hour to notice because the file that caused it was untracked and therefore invisible, and was found only when an unrelated agent tripped over it and reported that the suite would not collect.

**How somebody ends up here**: they write a test for something in `tools/`, reach for the obvious `sys.path.insert(0, TOOLS)`, and break six files they have never opened. Their own file passes in isolation. A scoped run says nothing — the damage is to modules that never import theirs.

## Root cause

`tools/wish.py` and the `wish/` package share a name. Whichever `sys.path` entry comes first wins, and a test that inserts `tools/` at the front makes `tools/wish.py` win for the rest of the process. `tools/session.py:43` also does an unconditional `sys.path.insert(0, TOOLS)` at import time, so importing it is enough on its own.

Confirmed still doing the unguarded permanent insert, counted rather than estimated:

* `tests/test_coldread.py`
* `tests/test_combatdrive.py`
* `tests/test_savecheck.py`
* `tests/test_outdoordrive.py`
* `tests/test_instance.py`
* `tests/test_genimports.py`

They do not break the suite **today** only because of collection order — pytest happens to reach them after the `wish` package has already been imported and cached. That is luck, not design: adding a test file whose name sorts earlier is enough to turn it red, which is exactly what happened.

## What would fix it

`tests/test_arrivalscene.py` has the pattern that works, added in `#182 (A driven save that arrives on a picture is reported as a failed load)`: load the module by file path with `importlib.util.spec_from_file_location`, with `tools/` on `sys.path` only for the duration of that one call and a `finally` that strips it. Nothing global changes and no other module can be affected.

Two smaller options, either of which would also do it and are worth considering first because they fix the cause rather than six symptoms:

* **Rename `tools/wish.py`.** The collision is the whole problem. `CLAUDE.md` records that `tools.wish` is reached into at run time by the application, so this is not free, but it is one change instead of six.
* **A `conftest.py` helper** every test uses, so the safe form is the easy form. Six copies of a guard is five chances to get it wrong.

## Testing

`pytest -q --collect-only` reports no errors — that is the whole assertion, and it fails today if any of the six is imported before the `wish` package.

A sharper test, if the helper route is taken: import one of the six in a subprocess *first* and assert `import wish; wish.backends` still resolves to the package. That fails against the current unguarded form and passes after, where a collect-only check only fails when the ordering happens to be unlucky.

Found on 2026-09-02 when a new test file broke collection, and confirmed by the code review of `#182 (A driven save that arrives on a picture is reported as a failed load)`, which counted the six and named them.

*Priority guessed at Medium: no player sees it, but it stops the entire suite dead, it is invisible until it fires, and the next person to write a test for anything in `tools/` will hit it. Donald recurates these by hand.*

**Comment by malcyon** [comment]
Took route 3, the conftest.py helper, and left `tools/wish.py`'s name alone.

**Why not route 2 (rename).** `tools/wish.py` is genuinely reached at runtime, not just at import: `wish/__main__.py:96` does `from tools.wish import subcommand` for the `wish export`/`wish import` subcommands, `wish.spec:45` names `"tools.wish"` as a PyInstaller hidden import, and `pyproject.toml` comments on it for the wheel's package list. It's also cited in six docs (`docs/129-one-binary.md`, `docs/106-releases.md`, `docs/122-release-testing.md`, `docs/97-editor.md`, `docs/README.md`, `docs/50-experiments.md`) and two other test files (`tests/test_paths.py`, `tests/test_packaging.py`). Not "one import line" -- a rename means touching the packaging spec and another agent's `docs/122-release-testing.md`, which I was told to sequence rather than just do. Route 2 is the right answer only if that cost turns out to be worth paying deliberately; it isn't a `junior-dev`-sized change today.

**The fix.** `tests/conftest.py` (which pytest always imports before any test file it applies to, regardless of collection order) now has `load_tools_module(name)`: imports the real `wish` package first, then loads `tools/<name>.py` by file path with `tools/` on `sys.path` only for the one `exec_module` call, in a `finally` that strips it -- the pattern `tests/test_arrivalscene.py` already used for #182 (A driven save that arrives on a picture is reported as a failed load), made shared. It also caches by name in `sys.modules` so two files asking for `session` get the same module object rather than each getting its own copy whose classes fail `isinstance` against the other's.

All six now call it instead of a bare `sys.path.insert(0, tools)`:
* `test_coldread.py`, `test_genimports.py` -- `X = load_tools_module("x")`, used as `X.thing` (unchanged from before, they already used the module as a namespace).
* `test_savecheck.py` -- unpacks the two names it used bare.
* `test_combatdrive.py`, `test_outdoordrive.py` -- unpack every name the old `from session import (...)` block imported.
* `test_instance.py` -- same shape; `TOOLS` stays (it's also used later for `porlaunch.sh`/`session.py` text checks and a real subprocess launch, unrelated to this).

**What I found, that isn't the fix.** Only 2 of the 6 -- `test_instance.py` and `test_genimports.py` -- actually reproduce `cannot import name 'backends' from 'wish'` in a direct, isolated reproduction (bare `import <file>` then `from wish import backends`, no pytest). The other four's unsafe pattern is real but gets accidentally saved most of the time: `tools/coldread.py`, `tools/drive.py` (imported transitively through `session`) and `tools/savecheck.py` all *also* do their own unconditional `sys.path.insert(0, repo_root)` at module import time, which happens to land after `tools/` and puts the real `wish` package back in front before anything asks for it. That's the same "luck, not design" this issue already names -- it's luck two layers deep, not a reason any of the four were actually safe.

**Testing.** New file `tests/test_toolshadowing.py`, parametrized over the six: spawns a subprocess that imports one of them directly (no pytest, no `conftest.py`) and then does `from wish import backends`, asserting that resolves. Confirmed red before the fix: reverted the six files and `conftest.py` to the versions at `HEAD` (an isolated `git worktree add --detach`, so this didn't touch anyone else's uncommitted work in `tools/session.py`), and got exactly `ImportError: cannot import name 'backends' from 'wish' (.../tools/wish.py)` for `test_instance` and `test_genimports` -- 2 of 6 failed, 4 passed for the accidental reason above. Restored the fix, all 6 pass. `diff`'d the restored files against the live ones and cleared `__pycache__` before trusting either run.

Whole suite in that same isolated worktree, `PYTHONPATH` pointed at it (so `wish` didn't leak in from the main tree's editable install): `pytest -q --collect-only` -- 2954 collected, no errors. `pytest -q` -- **2851 passed, 103 skipped**, 338s. `ruff check .` and `tools/genui.py --check` both clean.

New file: `tests/test_toolshadowing.py`. No row needed -- `tests/` has no `README.md`.
